const studentData=[{"id":1,"first_name":"Mortie","last_name":"Bertson","email":"mbertson0@ocn.ne.jp","gender":"Male"},
{"id":2,"first_name":"Sadie","last_name":"Utton","email":"sutton1@sphinn.com","gender":"Female"},
{"id":3,"first_name":"Weylin","last_name":"Stanbury","email":"wstanbury2@nps.gov","gender":"Male"},
{"id":4,"first_name":"Ric","last_name":"MacCague","email":"rmaccague3@comcast.net","gender":"Male"},
{"id":5,"first_name":"Brunhilde","last_name":"Ellett","email":"bellett4@statcounter.com","gender":"Female"},
{"id":6,"first_name":"Dylan","last_name":"Acres","email":"dacres5@domainmarket.com","gender":"Male"},
{"id":7,"first_name":"Nicol","last_name":"Quantrell","email":"nquantrell6@cnn.com","gender":"Male"},
{"id":8,"first_name":"Amos","last_name":"Milbourne","email":"amilbourne7@constantcontact.com","gender":"Agender"},
{"id":9,"first_name":"Shelby","last_name":"Pembridge","email":"spembridge8@shop-pro.jp","gender":"Male"},
{"id":10,"first_name":"Arlen","last_name":"Dallander","email":"adallander9@devhub.com","gender":"Male"},
{"id":11,"first_name":"Katharyn","last_name":"Gamon","email":"kgamona@hatena.ne.jp","gender":"Female"},
{"id":12,"first_name":"Eugene","last_name":"Ianson","email":"eiansonb@cnn.com","gender":"Male"},
{"id":13,"first_name":"Benjamen","last_name":"Quinney","email":"bquinneyc@bizjournals.com","gender":"Male"},
{"id":14,"first_name":"Scott","last_name":"Gliddon","email":"sgliddond@china.com.cn","gender":"Male"},
{"id":15,"first_name":"Cassius","last_name":"McKimm","email":"cmckimme@elpais.com","gender":"Male"},
{"id":16,"first_name":"Melitta","last_name":"Broyd","email":"mbroydf@wsj.com","gender":"Female"},
{"id":17,"first_name":"Simmonds","last_name":"Kembley","email":"skembleyg@alibaba.com","gender":"Male"},
{"id":18,"first_name":"Frasier","last_name":"Caslane","email":"fcaslaneh@elegantthemes.com","gender":"Male"},
{"id":19,"first_name":"Sallee","last_name":"Chetwin","email":"schetwini@drupal.org","gender":"Female"},
{"id":20,"first_name":"Filbert","last_name":"Gittins","email":"fgittinsj@shareasale.com","gender":"Male"}]

module.exports={studentData}